runtime: python39
entrypoint: gunicorn -b :$PORT --timeout 120 main:app
service: esekai
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  FLASK_ENV: production

readiness_check:
  app_start_timeout_sec: 180
